name: Mend Security Scan

on:
  push:
    branches: [ dev ]

jobs:
  security-scan:
    name: Mend Security Scan
    runs-on: windows-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Download Mend CLI
        run: |
          Invoke-WebRequest -Uri "https://downloads.mend.io/cli/windows_amd64/mend.exe" -OutFile "mend.exe"
        shell: pwsh
      
      - name: Run Mend Scan
        shell: pwsh
        env:
          MEND_EMAIL: ${{ secrets.MEND_EMAIL }}
          MEND_USER_KEY: ${{ secrets.MEND_USER_KEY }}
        run: |
          ./mend.exe dep -u -s "BenF Demo//GHC_Pipeline//ASPN_DEP"

      
      - name: Upload Scan Results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: mend-scan-results
          path: |
            whitesource/**
            .whitesource
          retention-days: 7
